### ISSUE TITLE
把指定用户弹幕作为同传弹幕处理

### ISSUE THREAD

**Issue by superybq** [eric2788/bilibili-jimaku-filter#10]
遇到有些直播间同传不按套路出牌,直接就是弹幕形式的,比如sunyeojin家的同传man,url:https://live.bilibili.com/6632844
![image](https://user-images.githubusercontent.com/20632962/103086086-96ecda00-461e-11eb-928c-0c5476e35f8c.png)

**Comment by eric2788** [comment]
你的功能请求已接受

**Comment by eric2788** [comment]
已更新版本 v0.8.1
