### ISSUE TITLE
Chrome加载css,js报错

### ISSUE THREAD

**Issue by superybq** [eric2788/bilibili-jimaku-filter#11]
Chrome加载css,js报错,Chrome版本:87.0.4280.88,网络是电信
![image](https://user-images.githubusercontent.com/20632962/103469497-a992ac00-4da0-11eb-8123-2c4b99bda058.png)
![image](https://user-images.githubusercontent.com/20632962/103469578-7997d880-4da1-11eb-8278-0bfbadf5b5f0.png)

加载报错结果:
![image](https://user-images.githubusercontent.com/20632962/103469543-13ab5100-4da1-11eb-8818-69afa0f64384.png)

**Comment by eric2788** [comment]
自己能直連 bootstrap cdn 鏈接嗎？

**Comment by eric2788** [comment]
所以國內是無法存取那個bootstrap cdn節點嗎？
怎麼我這插件出了一個月，一直沒人跟我說這件事  (╯°Д°)╯︵ ┻━┻
我還以為正常一直沒管

**Comment by superybq** [comment]
前段时间可以连,这两三天清过缓存之后才发现的

**Comment by eric2788** [comment]
好吧，新的國內CDN節點會在下個版本推出，在這之前會連帶幾個小功能一起更新

**Comment by eric2788** [comment]
v0.9.2 已更新，已轉為國內節點
