### ISSUE TITLE
请求增加直播间匹配

### ISSUE THREAD

**Issue by ssrkaze** [eric2788/bilibili-jimaku-filter#13]
**你的请求功能是不是基于一个问题 ？ 请描述**
当直播间是因为某种活动而开启的时候，页面的URL会变成
`https://www.bilibili.com/blackboard/live/(.*)`
这种形式的，此时同传弹幕过滤没有开启

**描述一下解决方法**
无
**补充内容**
无

**Comment by eric2788** [comment]
其实我有尝试过支援大海报活动房间，但发现房间直播元素采用的是iframe，火狐因为特殊原因没办法直接支援。目前因为活动房间实在不多，还没有更多大海报房间让我做更多实验，因此很难去做支援。
总括来说是我需要活动房间做大量测试，但活动房间出现次数太少了，导致我很难去做支援

**Comment by eric2788** [comment]
https://ngabbs.com/read.php?pid=489470484&opt=128

**Comment by eric2788** [comment]
v0.10.1 已更新。

**Comment by ssrkaze** [comment]
感谢更新。
