### ISSUE TITLE
B站直播间弹幕无法持续更新

### ISSUE THREAD

**Issue by G11sleeping** [eric2788/bilibili-jimaku-filter#14]
**描述问题**
今天B站直播间内的弹幕无法持续更新了.
经过测试关闭插件后可以加载。再打开插件又无法加载弹幕。
打开插件时刷新可以加载部分弹幕，但是后续弹幕无法加载。

**F12截图**
打开 debug level 然后 F12 [截图]
![dllhost_0yAbc24rmS](https://user-images.githubusercontent.com/75628773/118229698-0a549280-b4bf-11eb-8133-bfae939701e0.jpg)
![msedge_DK29MzGpd3](https://user-images.githubusercontent.com/75628773/118229566-cbbed800-b4be-11eb-93f2-41caa43fa584.png)
![msedge_ypZPdhulgT](https://user-images.githubusercontent.com/75628773/118229578-d24d4f80-b4be-11eb-9499-bdfe0ffceda5.png)

**你的配置**
 - 浏览器版本 Edge 92.0.884.2 (官方内部版本) dev (64 位)
 - 使用的插件版本  0.10.9

**Comment by eric2788** [comment]
剛剛自己測試了一下，firefox也不行，看來是b站更新了JSON格式，先暫時停用直到等下一個版本更新吧，我研究一下

**Comment by eric2788** [comment]
@G11sleeping 檢查一下版本 v0.11.2 修復了沒有, 把結果在這裏告訴一下

**Comment by G11sleeping** [comment]
我等Edge版更新了看看怎么样= =

**Comment by WilliamLuuu** [comment]
Firefox0.11.2版已修复

**Comment by eric2788** [comment]
好的，收到

> 
> 
> Firefox0.11.2版已修复
