### ISSUE TITLE
直播间弹幕无法更新

### ISSUE THREAD

**Issue by kafuuchino3** [eric2788/bilibili-jimaku-filter#15]
**描述问题**
直播间弹幕无法更新
包括插件内设置屏蔽的直播间，弹幕滚动栏不滚动，无法加载新弹幕。

**截图**
![image](https://user-images.githubusercontent.com/49277108/118482147-ec00c800-b746-11eb-9745-d7ce409f3ed1.png)

**你的配置**
 - 浏览器 Edge
 - 使用的插件版本 0.10.9

**Comment by kafuuchino3** [comment]
> **描述问题**
> 直播间弹幕无法更新
> 包括插件内设置屏蔽的直播间，弹幕滚动栏不滚动，无法加载新弹幕。
> 
> **截图**
> 
![image](https://user-images.githubusercontent.com/49277108/118482051-cecbf980-b746-11eb-8b8a-3add234b6317.png)

> 
> **你的配置**
> 
> * 浏览器 Edge
> * 使用的插件版本 0.10.9

**Comment by eric2788** [comment]
这个问题已经有人回报过 ( #14 )，是直播间更新了封包压缩方式的问题。
v0.11.2 版本已经修复了这个问题，请等待 Edge 版本的 v0.11.2 更新。
