### ISSUE TITLE
0.11.3版本无法使用

### ISSUE THREAD

**Issue by nanimouso** [eric2788/bilibili-jimaku-filter#16]
**描述问题**
chrome浏览器自动更新插件到最新版本后，此插件的基本功能在直播间内无法实现，找不到同传弹幕框，同时其他的功能和按钮也一并消失了。

**如何导致**
步骤讲述如何导致问题:
1. 进入 'https://live.bilibili.com/21396545'

2. 无法使用该插件的所有功能

**理应出现的运作**
本应该有同传框，以及一些按钮，比如记录同传弹幕等，全部都没有

**F12截图**
![image](https://user-images.githubusercontent.com/77824629/129898909-d72a3900-7509-47da-9e5e-ff683ce77882.png)

**你的配置**
 - 浏览器为chrome最新版本
 - 使用的插件版本为0.11.3

**额外补充**

**Comment by eric2788** [comment]
Console 錯誤截圖一下

**Comment by eric2788** [comment]
![image](https://user-images.githubusercontent.com/6276840/129899242-5b013261-86d2-4750-a177-2e3b83c2cc59.png)

umm 我有

不過切換按鈕好像不見了，要修復一下

**Comment by eric2788** [comment]
好，問題大致上了解了，應該是按鈕元素問題，等我更新

**Comment by eric2788** [comment]
更新了 v0.11.4 看一下問題修了沒有，雖然好像了解了但又挺玄的

**Comment by nanimouso** [comment]
> Console 錯誤截圖一下

我的console那边没有报错，extension里面没有error提示，挺玄幻的，我试一下0.11.4

**Comment by nanimouso** [comment]
> 更新了 v0.11.4 看一下問題修了沒有，雖然好像了解了但又挺玄的

目前是下播状态，按钮是恢复了，似乎能用，明天如果有直播的话我再确认一下修复成功。
总之感谢。

**Comment by eric2788** [comment]
太久了，我先关串。如果发现有问题你可以重新开串或者开新issue
