### ISSUE TITLE
建议增加弹幕从上向下添加新弹幕的选项

### ISSUE THREAD

**Issue by sakurairsora** [eric2788/bilibili-jimaku-filter#17]
因为从下往上添加会带来分享给他人看的话会很不方便的问题，所以希望能增加这样的显示方式

**Comment by eric2788** [comment]
> 
> 
> 雖然但是，插件有一個同傳彈幕彈出式視窗功能 它就是上到下的

有这个功能你还需要上到下吗？回答是我就开工了
