### ISSUE TITLE
[Feature Request] Modifying background color of button list

### ISSUE THREAD

**Issue by Kennnnnnji** [eric2788/bilibili-jimaku-filter#3]
When using a dark style script for bilibili, the default white background of the button list down the player would be really annoying, and it is not changeable in settings.
![image](https://user-images.githubusercontent.com/34367558/101353481-a229d100-38ce-11eb-8602-754ac01efed9.png)
I hope we can have a option in settings to change this box's background color.
![image](https://user-images.githubusercontent.com/34367558/101353533-b66dce00-38ce-11eb-8db1-1335888b0609.png)

**Comment by eric2788** [comment]
Marked, thanks for your request, I will add this feature to the next release.

**Comment by eric2788** [comment]
v0.0.5 has been released
