### ISSUE TITLE
[Feature Request] Remembering jimaku box size

### ISSUE THREAD

**Issue by Kennnnnnji** [eric2788/bilibili-jimaku-filter#4]
We can change the size of jimaku box now, but it will resize the next time opening a page.
I hope the extension can remember the size (height and width).
In fact, it would be also great if we can manually **set the size of box in settings**.

**Comment by eric2788** [comment]
Well I think it's not hard for user to re-manipulate their jimaku box......
Also the size of the box is auto fit to your page, specific the width is not a good idea, but the height may be considered.
Anyway thanks for your request

**Comment by eric2788** [comment]
Accepted Feature Requests:
- Remember the state of the box while last full screen
- Customizable the height of jimaku box

**Comment by eric2788** [comment]
v0.0.5 has been released.
