### ISSUE TITLE
聽說chrome要把三個勾選取消才能用？

### ISSUE THREAD

**Issue by eric2788** [eric2788/bilibili-jimaku-filter#5]
@Kennnnnnji 看你的截圖也是把那三個勾選取消了吧，但我本人使用chrome測試是只需要取消勾選 僅限虛擬主播就可以，請問你用的瀏覽器跟我的是有什麼不一樣的嗎？

![your-image](https://user-images.githubusercontent.com/34367558/101353481-a229d100-38ce-11eb-8602-754ac01efed9.png)

我的chrome版本

![image](https://user-images.githubusercontent.com/6276840/101483291-ec748600-3992-11eb-9107-d1c674f5f456.png)

**Comment by Kennnnnnji** [comment]
![image](https://user-images.githubusercontent.com/34367558/101489807-7117d200-399c-11eb-8236-6ccc9f7a42ae.png)
我目前设置如上

**Comment by eric2788** [comment]
啟用記錄功能卻沒有下載字幕按鈕？ 🤔

**Comment by Kennnnnnji** [comment]
现在有下载按钮（之前截图的时候没有选择第二个选项）
只要取消第三个选项应该就能正常使用

**Comment by eric2788** [comment]
> 现在有下载按钮（之前截图的时候没有选择第二个选项）
> 只要取消第三个选项应该就能正常使用

原來如此
因為我聽到不止一個說要取消三個勾選才能用
所以我就覺得是不是我的測試有問題
現在看來好像是沒問題 🤔

**Comment by eric2788** [comment]
不管如何，感谢你的解答。
如果下次有人提到这个问题我就可以把这楼发给他了，谢谢啦。
