### ISSUE TITLE
功能请求 一键导出导入设置

### ISSUE THREAD

**Issue by G11sleeping** [eric2788/bilibili-jimaku-filter#9]
**你的请求功能是不是基于一个问题 ？ 
由于使用chrome内核的edge，无法实时更新只能选择卸载重装
每次卸载重装的过程有设置需要重新设置

**描述一下解决方法**
导出按钮，导出设置为一个文档
导入按钮，导入文档设置自动设置好

**Comment by eric2788** [comment]
請問一下，chrome那個更新而不影響設定的方法對edge是無效的嗎？

**Comment by G11sleeping** [comment]
那个文件夹是指一开始安装时加载的文件夹吗？
就是不改变加载位置就会覆盖安装插件？
我平时解压出来后面自带版本后缀安装就成2个了
都是删了再安装的

也就是每次重新安装时要和以前加载的目录一致？

感觉还是搞个设置导出方便= =

**Comment by eric2788** [comment]
原本方法是：资料夹不变，只变更资料夹内的内容
因为未封装项目是动态加载

不过导入导出设定功能也不是不能加，只是最近有一个bug我需要研究一下如何修复，预计这个功能会连同那个bug修好后再一起推出新版本

**Comment by G11sleeping** [comment]
好的谢谢回复，麻烦了

**Comment by eric2788** [comment]
v0.0.7 版本已更新。
